language: ruby
cache: bundler
branches:
  only: master

rvm:
  - 2.2
  - 2.3
  - 2.4

gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.2.0.gemfile
  - gemfiles/rails4.2.8.gemfile
  - gemfiles/rails5.0.0.gemfile
  - gemfiles/rails5.0.1.gemfile

sudo: required

bundler_args: --no-deployment

before_script:
  - sudo cp /usr/share/doc/mysql-server-5.6/examples/my-default.cnf /usr/share/mysql/my-default.cnf

script: bundle exec rake test

matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails3.2.gemfile
