language: ruby

rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.1

gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile

sudo: false

bundler_args: --no-deployment

script: bundle exec rake test

matrix:
  exclude:
    - rvm: 2.4.1
      gemfile: gemfiles/rails3.2.gemfile
