language: ruby

rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.1

gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile

sudo: required

bundler_args: --no-deployment

before_script:
  - sudo cp /usr/share/doc/mysql-server-5.6/examples/my-default.cnf /usr/share/mysql/my-default.cnf

script: bundle exec rake test

matrix:
  exclude:
    - rvm: 2.4.1
      gemfile: gemfiles/rails3.2.gemfile
