# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
        environment:
          LOG_LEVEL: DEBUG
      - image: circleci/mysql:5.7
        environment:
          LOG_LEVEL: DEBUG

    steps:
      - checkout
      - run: echo ‘/usr/lib/postgresql/9.6/bin/:$PATH’ >> $BASH_ENV


      - run: bundle install --jobs=4 --path vendor/bundle

      # Database setup
      # - run: bundle exec rake db:create
      # - run: bundle exec rake db:schema:load

      - run: mysql --version
      - run: mysqld --version
      - run: rake test
